name: Deploy to staging

concurrency: 1

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: |
              pip install uv
              databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_DEMO_WEST_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging

  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle run datakickstart_dabs_job --refresh-all
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_DEMO_WEST_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging